[project]
name = "micrograd-np"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "numpy>=2.3.5",
    "pytest>=9.0.2",
    "torch>=2.9.1",
]
